const express = require('express');
const cors = require('cors');

const app = express();
const PORT = 3001;

// Enable CORS for React Native
app.use(cors());
app.use(express.json());

// Mock transactions data
const mockTransactions = {
  items: [
    {
      id: 'a0dff53e-4562348-4fe7-bcd5-e9d41a743c3b24',
      paymentProcessorId: '8584e595-4aee-47e6-91fa-9aabd2cd2150',
      date: '2024-04-15T14:30:31.256695Z',
      baseAmount: 99999999.99,
      totalAmount: 99999999.99,
      surchargeAmount: 0,
      surchargePercentage: 0,
      currencyCode: 'USD',
      currencyId: 1,
      merchant: 'Andrii Test Merchant',
      merchantId: 'de24c2e8-5c42-49e4-92f5-890fea10549e',
      operationMode: 'PayNow',
      paymentMethodType: 'ElectronicCheck',
      paymentMethodTypeId: 2,
      paymentMethodName: 'EFT',
      customerName: '2602 Positive',
      customerCompany: 'Positive',
      customerPan: '****2222',
      cardTokenType: null,
      customerEmail: 'greg@test.com',
      customerPhone: '4313411221',
      status: 'Scheduled',
      statusId: 90,
      typeId: 1,
      type: 'AchDebit',
      batchId: null,
      source: {
        typeId: 2,
        type: 'ApiToken',
        id: '47e8d5b2-a62c-4d71-9294-927f2906a93e',
        name: 'Regression7.2',
      },
      availableOperations: [],
      amount: {
        baseAmount: 99999999.99,
        percentageOffAmount: 0,
        percentageOffRate: 0,
        cashDiscountAmount: 0,
        cashDiscountRate: 0,
        surchargeAmount: 0,
        surchargeRate: 0,
        tipAmount: 0,
        tipRate: 0,
        taxAmount: 0,
        taxRate: 0,
        totalAmount: 99999999.99,
      },
    },
    {
      id: '3',
      paymentProcessorId: '8584e595-4aee-47e6-91fa-9aabd2cd2150',
      date: '2024-04-15T14:30:31.256695Z',
      baseAmount: 100,
      totalAmount: 100,
      surchargeAmount: 0,
      surchargePercentage: 0,
      currencyCode: 'USD',
      currencyId: 1,
      merchant: 'Andrii Test Merchant',
      merchantId: 'de24c2e8-5c42-49e4-92f5-890fea10549e',
      operationMode: 'PayNow',
      paymentMethodType: 'ElectronicCheck',
      paymentMethodTypeId: 2,
      paymentMethodName: 'EFT',
      customerName: '2602 Positive',
      customerCompany: 'Positive',
      customerPan: '****2222',
      cardTokenType: null,
      customerEmail: 'greg@test.com',
      customerPhone: '4313411221',
      status: 'Scheduled',
      statusId: 90,
      typeId: 2,
      type: 'AchDebit',
      batchId: null,
      source: {
        typeId: 2,
        type: 'ApiToken',
        id: '47e8d5b2-a62c-4d71-9294-927f2906a93e',
        name: 'Regression7.2',
      },
      availableOperations: [],
      amount: {
        baseAmount: 100,
        percentageOffAmount: 0,
        percentageOffRate: 0,
        cashDiscountAmount: 0,
        cashDiscountRate: 0,
        surchargeAmount: 0,
        surchargeRate: 0,
        tipAmount: 0,
        tipRate: 0,
        taxAmount: 0,
        taxRate: 0,
        totalAmount: 100,
      },
    },
    {
      id: '234',
      paymentProcessorId: '8584e595-4aee-47e6-91fa-9aabd2cd2150',
      date: '2024-04-15T14:30:31.256695Z',
      baseAmount: 100,
      totalAmount: 100,
      surchargeAmount: 0,
      surchargePercentage: 0,
      currencyCode: 'USD',
      currencyId: 1,
      merchant: 'Andrii Test Merchant',
      merchantId: 'de24c2e8-5c42-49e4-92f5-890fea10549e',
      operationMode: 'PayNow',
      paymentMethodType: 'ElectronicCheck',
      paymentMethodTypeId: 2,
      paymentMethodName: 'EFT',
      customerName: '2602 Positive',
      customerCompany: 'Positive',
      customerPan: '****2222',
      cardTokenType: null,
      customerEmail: 'greg@test.com',
      customerPhone: '4313411221',
      status: 'Scheduled',
      statusId: 90,
      typeId: 5,
      type: 'AchDebit',
      batchId: null,
      source: {
        typeId: 2,
        type: 'ApiToken',
        id: '47e8d5b2-a62c-4d71-9294-927f2906a93e',
        name: 'Regression7.2',
      },
      availableOperations: [],
      amount: {
        baseAmount: 100,
        percentageOffAmount: 0,
        percentageOffRate: 0,
        cashDiscountAmount: 0,
        cashDiscountRate: 0,
        surchargeAmount: 0,
        surchargeRate: 0,
        tipAmount: 0,
        tipRate: 0,
        taxAmount: 0,
        taxRate: 0,
        totalAmount: 100,
      },
    },
    {
      id: '555',
      paymentProcessorId: '8584e595-4aee-47e6-91fa-9aabd2cd2150',
      date: '2024-04-15T14:30:31.256695Z',
      baseAmount: 100,
      totalAmount: 100,
      surchargeAmount: 0,
      surchargePercentage: 0,
      currencyCode: 'USD',
      currencyId: 1,
      merchant: 'Andrii Test Merchant',
      merchantId: 'de24c2e8-5c42-49e4-92f5-890fea10549e',
      operationMode: 'PayNow',
      paymentMethodType: 'ElectronicCheck',
      paymentMethodTypeId: 2,
      paymentMethodName: 'EFT',
      customerName: '2602 Positive',
      customerCompany: 'Positive',
      customerPan: '****2222',
      cardTokenType: null,
      customerEmail: 'greg@test.com',
      customerPhone: '4313411221',
      status: 'Scheduled',
      statusId: 90,
      typeId: 12,
      type: 'AchDebit',
      batchId: null,
      source: {
        typeId: 2,
        type: 'ApiToken',
        id: '47e8d5b2-a62c-4d71-9294-927f2906a93e',
        name: 'Regression7.2',
      },
      availableOperations: [],
      amount: {
        baseAmount: 100,
        percentageOffAmount: 0,
        percentageOffRate: 0,
        cashDiscountAmount: 0,
        cashDiscountRate: 0,
        surchargeAmount: 0,
        surchargeRate: 0,
        tipAmount: 0,
        tipRate: 0,
        taxAmount: 0,
        taxRate: 0,
        totalAmount: 100,
      },
    },
    {
      id: 'a0dff53e-4568-4fe7-bcd5-e9d41a742223c6663b',
      paymentProcessorId: '8584e595-4aee-47e6-91fa-9aabd2cd2150',
      date: '2024-04-15T14:30:31.256695Z',
      baseAmount: 100,
      totalAmount: 100,
      surchargeAmount: 0,
      surchargePercentage: 0,
      currencyCode: 'USD',
      currencyId: 1,
      merchant: 'Andrii Test Merchant',
      merchantId: 'de24c2e8-5c42-49e4-92f5-890fea10549e',
      operationMode: 'PayNow',
      paymentMethodType: 'ElectronicCheck',
      paymentMethodTypeId: 2,
      paymentMethodName: 'EFT',
      customerName: '2602 Positive',
      customerCompany: 'Positive',
      customerPan: '****2222',
      cardTokenType: null,
      customerEmail: 'greg@test.com',
      customerPhone: '4313411221',
      status: 'Scheduled',
      statusId: 90,
      typeId: 11,
      type: 'AchDebit',
      batchId: null,
      source: {
        typeId: 2,
        type: 'ApiToken',
        id: '47e8d5b2-a62c-4d71-9294-927f2906a93e',
        name: 'Regression7.2',
      },
      availableOperations: [],
      amount: {
        baseAmount: 100,
        percentageOffAmount: 0,
        percentageOffRate: 0,
        cashDiscountAmount: 0,
        cashDiscountRate: 0,
        surchargeAmount: 0,
        surchargeRate: 0,
        tipAmount: 0,
        tipRate: 0,
        taxAmount: 0,
        taxRate: 0,
        totalAmount: 100,
      },
    },
    {
      id: 'a0dff53e-4568-4fe7-bcd2225-e9d41a743c3b',
      paymentProcessorId: '8584e595-4aee-47e6-91fa-9aabd2cd2150',
      date: '2024-04-15T14:30:31.256695Z',
      baseAmount: 100,
      totalAmount: 100,
      surchargeAmount: 0,
      surchargePercentage: 0,
      currencyCode: 'USD',
      currencyId: 1,
      merchant: 'Andrii Test Merchant',
      merchantId: 'de24c2e8-5c42-49e4-92f5-890fea10549e',
      operationMode: 'PayNow',
      paymentMethodType: 'ElectronicCheck',
      paymentMethodTypeId: 2,
      paymentMethodName: 'EFT',
      customerName: '2602 Positive',
      customerCompany: 'Positive',
      customerPan: '****2222',
      cardTokenType: null,
      customerEmail: 'greg@test.com',
      customerPhone: '4313411221',
      status: 'Scheduled',
      statusId: 90,
      typeId: 16,
      type: 'AchDebit',
      batchId: null,
      source: {
        typeId: 2,
        type: 'ApiToken',
        id: '47e8d5b2-a62c-4d71-9294-927f2906a93e',
        name: 'Regression7.2',
      },
      availableOperations: [],
      amount: {
        baseAmount: 100,
        percentageOffAmount: 0,
        percentageOffRate: 0,
        cashDiscountAmount: 0,
        cashDiscountRate: 0,
        surchargeAmount: 0,
        surchargeRate: 0,
        tipAmount: 0,
        tipRate: 0,
        taxAmount: 0,
        taxRate: 0,
        totalAmount: 100,
      },
    },
    {
      id: 'a0dff53e-4533368-4fe7-bcd5-e9d41a743c3b',
      paymentProcessorId: '8584e595-4aee-47e6-91fa-9aabd2cd2150',
      date: '2024-04-15T14:30:31.256695Z',
      baseAmount: 100,
      totalAmount: 100,
      surchargeAmount: 0,
      surchargePercentage: 0,
      currencyCode: 'USD',
      currencyId: 1,
      merchant: 'Andrii Test Merchant',
      merchantId: 'de24c2e8-5c42-49e4-92f5-890fea10549e',
      operationMode: 'PayNow',
      paymentMethodType: 'ElectronicCheck',
      paymentMethodTypeId: 2,
      paymentMethodName: 'EFT',
      customerName: '2602 Positive',
      customerCompany: 'Positive',
      customerPan: '****2222',
      cardTokenType: null,
      customerEmail: 'greg@test.com',
      customerPhone: '4313411221',
      status: 'Scheduled',
      statusId: 7,
      typeId: 16,
      type: 'AchDebit',
      batchId: null,
      source: {
        typeId: 2,
        type: 'ApiToken',
        id: '47e8d5b2-a62c-4d71-9294-927f2906a93e',
        name: 'Regression7.2',
      },
      availableOperations: [],
      amount: {
        baseAmount: 100,
        percentageOffAmount: 0,
        percentageOffRate: 0,
        cashDiscountAmount: 0,
        cashDiscountRate: 0,
        surchargeAmount: 0,
        surchargeRate: 0,
        tipAmount: 0,
        tipRate: 0,
        taxAmount: 0,
        taxRate: 0,
        totalAmount: 100,
      },
    },
  ],
  total: 1,
};

// Transactions endpoint
app.get('/api/transactions', (req, res) => {
  console.log('Mock server: GET /api/transactions');
  console.log('Query parameters:', req.query);

  // Simulate some delay to mimic real API
  setTimeout(() => {
    res.json(mockTransactions);
  }, 100);
});

// Health check endpoint
app.get('/health', (req, res) => {
  res.json({status: 'OK', message: 'Mock server is running'});
});

// Root endpoint
app.get('/', (req, res) => {
  res.json({
    message: 'Arise Mock Server',
    endpoints: {
      transactions: '/api/transactions',
      health: '/health',
    },
  });
});

app.listen(PORT, () => {
  console.log(`Mock server running on http://localhost:${PORT}`);
  console.log(
    `Transactions endpoint: http://localhost:${PORT}/api/transactions`,
  );
});
