import {TRANSACTION_DETAIL_MESSAGES, UI_MESSAGES} from '@/constants/messages';

export const nativeIDs = `open-website-btn,
email-us-btn,phone-btn,1,2,3,4,5,6,7,8,9,0,⌫,
${TRANSACTION_DETAIL_MESSAGES.TITLE_CAPTURE_TRANSACTION},
${TRANSACTION_DETAIL_MESSAGES.TITLE_REFUND_TRANSACTION},
${UI_MESSAGES.SELECT_PAYMENT_METHOD},
${TRANSACTION_DETAIL_MESSAGES.CONFIRM_REFUND_BUTTON},
close-receipt,share-button,
${TRANSACTION_DETAIL_MESSAGES.VOID_BUTTON},
${TRANSACTION_DETAIL_MESSAGES.REFUND_BUTTON},
${TRANSACTION_DETAIL_MESSAGES.VOID_BUTTON},
${TRANSACTION_DETAIL_MESSAGES.VIEW_RECEIPT_BUTTON},
${TRANSACTION_DETAIL_MESSAGES.CAPTURE_BUTTON},
`;
